// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhyscghkxsjwsczhviwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoeXNjZ2hreHNqd3Njemh2aXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjI0NDUsImV4cCI6MjA2NjkzODQ0NX0.SRhEaQqaEj1TVOhldrxVSQvquln0FBLQUlP4_jwII1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});